dist: trusty
language: python
python:
  - "3.6.1"
# command to install dependencies
before_install: cd src
install: pip install pyqt5
script: python -m unittest discover tests -v
branches:
  only:
    - master
notifications:
  slack: ngreen:rIZV8SbYFa6RJrxThTyNHd6U